# Generated by Django 4.0.3 on 2022-03-11 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentification", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MangaLibrairy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_manga", models.BigIntegerField()),
                ("chapitre", models.FloatField()),
                (
                    "id_profil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentification.profil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnimeLibrairy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_anime", models.BigIntegerField()),
                ("episode", models.FloatField()),
                ("saison", models.IntegerField()),
                (
                    "id_profil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentification.profil",
                    ),
                ),
            ],
        ),
    ]
