# Generated by Django 4.0.3 on 2022-03-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0001_initial"),
        ("manganime", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="animelibrairy",
            unique_together={("id_profil", "id_anime")},
        ),
        migrations.AlterUniqueTogether(
            name="mangalibrairy",
            unique_together={("id_profil", "id_manga")},
        ),
    ]
