# Generated by Django 4.0.3 on 2022-03-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
        ('manganime', '0002_alter_animelibrairy_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animelibrairy',
            old_name='id_profil',
            new_name='profil',
        ),
        migrations.AlterUniqueTogether(
            name='animelibrairy',
            unique_together={('profil', 'id_anime')},
        ),
    ]
