# Generated by Django 4.0.3 on 2022-03-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
        ('manganime', '0003_rename_id_profil_animelibrairy_profil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mangalibrairy',
            old_name='id_profil',
            new_name='profil',
        ),
        migrations.AlterUniqueTogether(
            name='mangalibrairy',
            unique_together={('profil', 'id_manga')},
        ),
    ]
