# Generated by Django 4.0.3 on 2022-03-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
        ('manganime', '0004_rename_id_profil_mangalibrairy_profil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mangalibrairy',
            old_name='profil',
            new_name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='mangalibrairy',
            unique_together={('profile', 'id_manga')},
        ),
    ]
