# Generated by Django 4.0.3 on 2022-03-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_rename_profil_profile'),
        ('manganime', '0005_rename_profil_mangalibrairy_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animelibrairy',
            old_name='profil',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='animelibrairy',
            old_name='saison',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='mangalibrairy',
            old_name='chapitre',
            new_name='chapter',
        ),
        migrations.AlterUniqueTogether(
            name='animelibrairy',
            unique_together={('profile', 'id_anime')},
        ),
    ]
