# Generated by Django 4.0.3 on 2022-03-18 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('id_user_applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_applicant', to=settings.AUTH_USER_MODEL)),
                ('id_user_receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_receiving', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id_user_applicant', 'id_user_receiving')},
            },
        ),
    ]
